This is an OpenEmbedded only patch to make the code buildable in
the OpenEmbedded environment.

Index: ixp400-eth-1.5/Makefile
===================================================================
--- /dev/null	1970-01-01 00:00:00.000000000 +0000
+++ ixp400-eth-1.5/Makefile	2006-06-22 16:11:15.000000000 +0200
@@ -0,0 +1,30 @@
+OSAL_INC = /usr/include/ixp4xx/osal
+CSR_INC =  /usr/include/ixp4xx/csr
+
+obj-m := ixp400_eth.o
+
+CFLAGS_ixp400_eth.o = -DWall \
+          -I$(CSR_INC) \
+          -I$(OSAL_INC) \
+          -I$(OSAL_INC)/os/linux \
+          -I$(OSAL_INC)/os/linux/modules \
+          -I$(OSAL_INC)/os/linux/modules/ioMem \
+          -I$(OSAL_INC)/os/linux/modules/core \
+          -I$(OSAL_INC)/os/linux/modules/bufferMgt \
+          -I$(OSAL_INC)/os/linux/core/  \
+          -I$(OSAL_INC)/os/linux/platforms \
+          -I$(OSAL_INC)/os/linux/platforms/ixp400 \
+          -I$(OSAL_INC)/os/linux/platforms/ixp400/ixp425 \
+          -I$(OSAL_INC)/modules \
+          -I$(OSAL_INC)/modules/bufferMgt \
+          -I$(OSAL_INC)/modules/ioMem \
+          -I$(OSAL_INC)/modules/core \
+          -I$(OSAL_INC)/platforms \
+          -I$(OSAL_INC)/platforms/ixp400 \
+	  $(IX_CFLAGS)
+
+default:
+	$(MAKE) ARCH=arm CROSS_COMPILE=$(LINUX_CROSS_COMPILE) $(KERNEL_VERBOSE) symverfile=$(IXP4XX_CSR_SYMVERS) -C $(KSRC) SUBDIRS=$(PWD) modules
+
+clean:
+	rm -f ixp400_eth.ko
