 Makefile                |    2 +-
 os/linux/make/macros.mk |    4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

Index: ixp_osal/Makefile
===================================================================
--- ixp_osal/Makefile.orig	2006-06-19 16:19:17.000000000 +0200
+++ ixp_osal/Makefile	2006-06-19 16:40:48.000000000 +0200
@@ -185,7 +185,7 @@
 INCLUDE_DIRS = include $(OSAL_DIRS:%=$(MAIN_INC_PREFIX)/%) $(OSAL_DIRS:%=$(OS_INC_PREFIX)/%)  
 
 ifeq ($(IX_OSAL_MK_HOST_OS), linux)
-INCLUDE_DIRS += $(LINUX_SRC)/include/asm-arm/arch-ixp425/
+INCLUDE_DIRS += $(LINUX_SRC)/include/asm-arm/arch-ixp4xx/
 endif
 
 CFLAGS += $(INCLUDE_DIRS:%=-I%) 
@@ -449,7 +449,7 @@
 endif
 
 DEPS := $(ALL_OBJ:.o=.d)
-include $(DEPS)
+-include $(DEPS)
 
 
 
Index: ixp_osal/os/linux/make/macros.mk
===================================================================
--- ixp_osal/os/linux/make/macros.mk.orig	2006-06-19 16:19:17.000000000 +0200
+++ ixp_osal/os/linux/make/macros.mk	2006-06-19 16:40:18.000000000 +0200
@@ -88,10 +88,10 @@
 # Compiler & linker options
 
 # Compiler flags
-LINUX_MACH_CFLAGS := -D__LINUX_ARM_ARCH__=5 -mcpu=xscale -mtune=xscale
+LINUX_MACH_CFLAGS := -D__LINUX_ARM_ARCH__=5 -mtune=xscale
 
 CFLAGS := -D__KERNEL__ -I$(LINUX_SRC)/include -Wall -Wno-trigraphs -fno-common \
-          -pipe -mapcs-32 -mshort-load-bytes -msoft-float -DMODULE \
+          -pipe -msoft-float -DMODULE \
           -D__linux -DCPU=33 -DXSCALE=33 $(LINUX_MACH_CFLAGS) -DEXPORT_SYMTAB
 
 # Linux linker flags
